= Introduction =
* Presented by Lightcast (formerly Burning Glass) at the OECD premises
* Lightcast is used by ELS and Innovation Unit
** Alignment between demand and supply
* ISCO for International Standard Classification of Occupation. Standardization started in Europe
* Geographical coverage: good for US and Europe
* Skills: specialized skills (hard skill, technical skills: node.js), common skills (soft skill that can be patent to many occupations: project management)
* Issue with big data: a lot of noise in job occupations that does not reflect clearly the market dynamic. Data transformation and cleansing to identifyy duplicated job.

= Lightcast to address analytical questions ? =

== How green economy is evolving in the countries ? ==
** Demand for green skill in online job vacancies > which taxonomy to use > esco skill taxonomy no longer enough > need for a design phase > the european green deal

** Look at the job description: extract eg : renewable energy, energy management, carbon foot printing

== How much remote work is present in each labour market ? ==
** Looking at the job description or in the title : word like (remote), next to the location
** > Presence of remote working mentions in online job vacances > what are the key words to search for > two step approach > 
** Multilingual context
** Analysis -> % remote over time or delta vs a reference date

== How 'complex' are occupations dna the skills employers require ? ==

* Higher diversity -> An occupation requires more skills -> it is more 'complex' (
* Ubiquity : how many occupations require this skill ? -? communications and Excel has a high ubiquity

== Lightcast research in 2023 --> Digital Skills ? ==
