Presented by Lightcast (formerly Burning Glass) at the OECD premises

* Lightcast is used by ELS and Innovation Unit
** Alignment between demand and supply

* ISCO for International Standard Classification of Occupation. Standardization started in Europe
* Geographical coverage: good for US and Europe
* Skills: specialized skills (hard skill, technical skills: node.js), common skills (soft skill that can be patent to many occupations: project management)
* Issue with big data: a lot of noise in job occupations that does not reflect the market dynamic. Data transformation and cleansing to identifiy duplicated job.
* Analytical questions: 

== How green economy is evolving in the countries ==
** Demand for green skill in online job vacancies > which taxonomy to use > esco skill taxonomy no longer enough > need for a design phase > the european green deal

** Look at the job description: extract eg : renewable energy, energy management, carbon foot printing
*** 
== How much remote work is present in each labour market ==
